### ISSUE TITLE
Unhandled Exception: `Null` is not a subtype of type `String`

### ISSUE THREAD

**Issue by izzalDev** [lamnhan066/dmg#1]
#### Description
An error occurs when running the application with the command `dart run dmg`, resulting in the following message:

```bash
Unhandled exception:
type 'Null' is not a subtype of type 'String' in type cast
#0      main (file:///Users/izzal/.pub-cache/hosted/pub.dev/dmg-0.0.5/bin/dmg.dart:37:53)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#2      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

#### Steps to Reproduce
1. Run the command `dart run dmg`.

#### Expected Behavior
The command should run without any errors.

#### Actual Behavior
The command results in an exception that prevents the application from running.

#### Environment
- **OS:** macOS Sonoma 14.6.1
- **Flutter:** 3.22.3
- **Dart:** 3.4.4
- **Package version:** 0.0.5

#### Additional Information
No additional information at this time.

**Comment by lamnhan066** [comment]
Hi @izzalDev 

Regarding the error logs,  you’re missing the `--sign-certificate` flag. The package currently doesn’t automatically detect the certificate, so we need to add it ourselves.

**Comment by izzalDev** [comment]
Thanks @lamnhan066 

I have tried running the command `dart run dmg --sign-certificate "Developer ID Application: Your Company"`. The process runs smoothly until the code signing step for the DMG file. However, when the notarization process starts, I encounter an unhandled exception with the following error message:

```bash
Cleaning build...
Cleaned
Flutter release...
Released
Code signing for the APP...
Signed
Building DMG...
Built
Code signing for the DMG...
Signed
Notarizing...
Unhandled exception:
Null check operator used on a null value
#0      main (file:///Users/izzal/.pub-cache/hosted/pub.dev/dmg-0.0.5/bin/dmg.dart:77:25)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#2      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

To troubleshoot further, I also tried running the command with the `--notary-profile "NotaryProfile"` option, but the output remains the same. The issue persists during the notarization step.

**Comment by lamnhan066** [comment]
Hi @izzalDev 

I have added the `verbose` flag to print some useful logs to the `main` branch. You can add the `--verbose` flag to see more details about the issue.

Before that, you need to add this dependency overrides to the `pubspec.yaml`:

```yaml
dependency_overrides:
  dmg:
    git: https://github.com/lamnhan066/dmg
```

Please comment the results here if possible so I can fix the issue more easily. Thank you.
